name: Android CI

on:
  push:
    branches: [ lsp ]
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Debug
      run: ./gradlew buildDebug
    - name: Upload Debug artifact
      uses: actions/upload-artifact@v2
      with:
        name: lspatch-debug
        path: |
          out/lspatch.jar
          out/manager-debug.apk

    - name: Build Release
      run: ./gradlew buildRelease
    - name: Upload Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: lspatch-release
        path: |
          out/lspatch.jar
          out/manager-release.apk
